// Wraps `prisma generate` so it runs even when the only connection string
// present is named something other than DATABASE_URL (see
// resolveDatabaseUrl.mjs) — prisma generate validates the schema's
// datasource block, which requires the env var it references to resolve.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { resolveDatabaseUrl } from "./resolveDatabaseUrl.mjs";

// Vercel injects env vars directly into process.env — no .env file exists
// there. Locally, load one if present so this script behaves the same way
// running here as it will in Vercel's build.
try {
  process.loadEnvFile();
} catch {
  // No local .env — fine, e.g. in Vercel's build environment.
}

const { url, source } = resolveDatabaseUrl();
console.log(`[prisma generate] using connection string from ${source}`);

execFileSync("prisma", ["generate"], {
  stdio: "inherit",
  env: { ...process.env, DATABASE_URL: url },
});

// Embed the generated WASM query compiler's bytes directly into a committed
// (but generated, git-ignored) TS module instead of leaving Prisma to read
// it from disk at runtime — see packages/db/src/wasmCompilerPatch.ts for
// why: Vercel's output-file tracer was proven, three separate times, not to
// reliably include Prisma-generated runtime files even when a local build's
// own trace said it would. Embedding the bytes as a JS constant removes the
// file-system dependency entirely rather than trying again to get tracing
// to work.
const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, "..");
const repoRoot = path.resolve(packageRoot, "../..");
const wasmPath = path.join(repoRoot, "node_modules/.prisma/client/query_compiler_bg.wasm");
const outDir = path.join(packageRoot, "src/generated");
const outFile = path.join(outDir, "queryCompilerWasm.ts");

if (existsSync(wasmPath)) {
  const bytes = readFileSync(wasmPath);
  mkdirSync(outDir, { recursive: true });
  writeFileSync(
    outFile,
    `// Auto-generated by packages/db/scripts/generate.mjs — do not edit.\n` +
      `// Base64 of node_modules/.prisma/client/query_compiler_bg.wasm (${bytes.length} bytes).\n` +
      `export const QUERY_COMPILER_WASM_BASE64 = "${bytes.toString("base64")}";\n`,
  );
  console.log(`[prisma generate] embedded query_compiler_bg.wasm (${bytes.length} bytes) into src/generated/queryCompilerWasm.ts`);
} else {
  console.warn(`[prisma generate] WARNING: expected WASM query compiler not found at ${wasmPath} — driver-adapter client generation may have changed.`);
}
